version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=iffdev
      - TZ=$TIMEZONE
      - PGTZ=$TIMEZONE
    ports:
      - "5432:5432"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:1323"
    environment:
      - DB_DRIVER=postgres
      - DB_SOURCE=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/iffdev?sslmode=disable
      - MIGRATION_URL=file://db/migration
      - HTTP_SERVER_ADDRESS=0.0.0.0:8080
      - ACCESS_TOKEN_SYMMETRIC_KEY=12345678901234567890123456789012
      - REFRESH_TOKEN_SYMMETRIC_KEY=123456789012345678901233323456789012
      - ACCESS_TOKEN_DURATION=15m
      - REFRESH_TOKEN_DURATION=24h
      - ALCHEMY_API_URL=https://eth-sepolia.g.alchemy.com/v2/i8RTBcKFG3U1qEUbUprJXDatOggaZxcE/
      - IFFNFT_CONTRACT_ADDRESS=0x507AA149A42012AD74C1E40E076a3f2391E13b61
    depends_on:
      - postgres
    entrypoint:
      [
        "/app/wait-for.sh",
        "postgres:5432",
        "--",
        "/app/start.sh"
      ]
    command: [ "/app/main" ]

