// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type GasPrice struct {
	ID        int64         `json:"id"`
	Average   sql.NullInt32 `json:"average"`
	CreatedAt sql.NullTime  `json:"createdAt"`
}

type IffNft struct {
	ID                         uuid.UUID `json:"id"`
	ProjectID                  int64     `json:"projectID"`
	UserWalletAddress          string    `json:"userWalletAddress"`
	NftProjectsContractAddress string    `json:"nftProjectsContractAddress"`
	NftProjectsCollectionName  string    `json:"nftProjectsCollectionName"`
	MintDate                   time.Time `json:"mintDate"`
	MintTransaction            string    `json:"mintTransaction"`
}

type NftProject struct {
	ID              uuid.UUID      `json:"id"`
	Name            string         `json:"name"`
	ContractAddress string         `json:"contractAddress"`
	CollectionName  string         `json:"collectionName"`
	ImageUri        sql.NullString `json:"imageUri"`
}

type ReportBlocklist struct {
	ID                uuid.UUID      `json:"id"`
	HttpAddress       string         `json:"httpAddress"`
	VerifiedAt        sql.NullTime   `json:"verifiedAt"`
	UserWalletAddress sql.NullString `json:"userWalletAddress"`
	CreatedAt         time.Time      `json:"createdAt"`
	DisprovedAt       sql.NullTime   `json:"disprovedAt"`
}

type ReportWhitelist struct {
	ID                uuid.UUID      `json:"id"`
	HttpAddress       string         `json:"httpAddress"`
	VerifiedAt        sql.NullTime   `json:"verifiedAt"`
	UserWalletAddress sql.NullString `json:"userWalletAddress"`
	CreatedAt         time.Time      `json:"createdAt"`
}

type Session struct {
	ID            uuid.UUID `json:"id"`
	WalletAddress string    `json:"walletAddress"`
	RefreshToken  string    `json:"refreshToken"`
	UserAgent     string    `json:"userAgent"`
	ClientIp      string    `json:"clientIp"`
	IsBlocked     bool      `json:"isBlocked"`
	ExpiresAt     time.Time `json:"expiresAt"`
	CreatedAt     time.Time `json:"createdAt"`
}

type User struct {
	ID            uuid.UUID      `json:"id"`
	FullName      sql.NullString `json:"fullName"`
	WalletAddress sql.NullString `json:"walletAddress"`
	CreatedAt     sql.NullTime   `json:"createdAt"`
	CountryCode   sql.NullString `json:"countryCode"`
	EmailAddress  sql.NullString `json:"emailAddress"`
	KycDate       sql.NullTime   `json:"kycDate"`
	TwitterName   sql.NullString `json:"twitterName"`
	BlockpassID   sql.NullInt64  `json:"blockpassID"`
	ImageUri      sql.NullString `json:"imageUri"`
	Nonce         sql.NullString `json:"nonce"`
}
