// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type AppliancesFromDiscordChannel struct {
	ID          uuid.UUID    `json:"id"`
	ChannelName string       `json:"channelName"`
	GuildID     string       `json:"guildID"`
	CreatedAt   time.Time    `json:"createdAt"`
	VerifiedAt  sql.NullTime `json:"verifiedAt"`
	IsApproved  sql.NullBool `json:"isApproved"`
}

type DiscordChannel struct {
	ID        uuid.UUID    `json:"id"`
	Name      string       `json:"name"`
	GuildID   string       `json:"guildID"`
	CreatedAt time.Time    `json:"createdAt"`
	LockedAt  sql.NullTime `json:"lockedAt"`
}

type GasPrice struct {
	ID        int64          `json:"id"`
	Average   sql.NullString `json:"average"`
	CreatedAt sql.NullTime   `json:"createdAt"`
}

type IffNft struct {
	ID                         uuid.UUID `json:"id"`
	ProjectID                  int64     `json:"projectID"`
	UserWalletAddress          string    `json:"userWalletAddress"`
	NftProjectsContractAddress string    `json:"nftProjectsContractAddress"`
	NftProjectsCollectionName  string    `json:"nftProjectsCollectionName"`
	MintDate                   time.Time `json:"mintDate"`
	MintTransaction            string    `json:"mintTransaction"`
}

type NftProject struct {
	ID              uuid.UUID `json:"id"`
	Name            string    `json:"name"`
	ContractAddress string    `json:"contractAddress"`
	CollectionName  string    `json:"collectionName"`
	ImageUri        string    `json:"imageUri"`
}

type ReportBlocklist struct {
	ID                uuid.UUID      `json:"id"`
	HttpAddress       string         `json:"httpAddress"`
	VerifiedAt        sql.NullTime   `json:"verifiedAt"`
	UserWalletAddress sql.NullString `json:"userWalletAddress"`
	CreatedAt         time.Time      `json:"createdAt"`
	DisprovedAt       sql.NullTime   `json:"disprovedAt"`
	GuildID           string         `json:"guildID"`
	GuildName         string         `json:"guildName"`
	ReporterName      string         `json:"reporterName"`
	ReporterAvatar    string         `json:"reporterAvatar"`
}

type ReportWhitelist struct {
	ID                uuid.UUID      `json:"id"`
	HttpAddress       string         `json:"httpAddress"`
	VerifiedAt        sql.NullTime   `json:"verifiedAt"`
	UserWalletAddress sql.NullString `json:"userWalletAddress"`
	CreatedAt         time.Time      `json:"createdAt"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	Wallet       string    `json:"wallet"`
	RefreshToken string    `json:"refreshToken"`
	UserAgent    string    `json:"userAgent"`
	ClientIp     string    `json:"clientIp"`
	IsBlocked    bool      `json:"isBlocked"`
	ExpiresAt    time.Time `json:"expiresAt"`
	CreatedAt    time.Time `json:"createdAt"`
}

type User struct {
	ID           uuid.UUID      `json:"id"`
	FullName     sql.NullString `json:"fullName"`
	Wallet       sql.NullString `json:"wallet"`
	CreatedAt    sql.NullTime   `json:"createdAt"`
	CountryCode  sql.NullString `json:"countryCode"`
	EmailAddress sql.NullString `json:"emailAddress"`
	KycDate      sql.NullTime   `json:"kycDate"`
	TwitterName  sql.NullString `json:"twitterName"`
	BlockpassID  sql.NullInt64  `json:"blockpassID"`
	ImageUri     sql.NullString `json:"imageUri"`
	Nonce        sql.NullString `json:"nonce"`
}
