basePath: /
definitions:
  api.renewAccessTokenResponse:
    properties:
      accessToken:
        type: string
      accessTokenExpiresAt:
        type: integer
    type: object
host: localhost:1323
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Ifandonlyif API
  version: "1.0"
paths:
  /api/fetchBlockListById:
    post:
      consumes:
      - '*/*'
      description: fetch blocklist by uuid
      parameters:
      - description: uuid
        in: body
        name: uuid
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: fetchBlockListById
      tags:
      - fetchBlockListById
  /api/getAllBlockLists:
    get:
      consumes:
      - '*/*'
      description: get all blocklists
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: getAllBlockLists
      tags:
      - getAllBlockLists
  /auth/fetchUserNfts:
    post:
      consumes:
      - '*/*'
      description: get mintable USER NFTS
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: fetchUserNfts
      tags:
      - fetchUserNfts
  /checkUri:
    post:
      consumes:
      - '*/*'
      description: fetch blocklist by uri
      parameters:
      - description: uri
        in: body
        name: uri
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: checkUri
      tags:
      - checkUri
  /code:
    post:
      consumes:
      - application/json
      description: register a new user
      parameters:
      - description: wallet
        in: body
        name: wallet
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "201":
          description: Created
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: code
      tags:
      - code
  /ethToUsd:
    get:
      consumes:
      - '*/*'
      description: get current 1 ETH to USD price
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ethToUsd
      tags:
      - ethToUsd
  /gasInfo:
    get:
      consumes:
      - '*/*'
      description: get 24 hours gas prices
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: gasInfo
      tags:
      - gasInfo
  /health:
    get:
      consumes:
      - '*/*'
      description: get the status of server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show the status of server.
      tags:
      - health
  /login:
    post:
      consumes:
      - application/json
      description: login
      parameters:
      - description: wallet
        in: body
        name: wallet
        required: true
        schema:
          type: string
      - description: signature
        in: body
        name: signature
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "201":
          description: Created
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: login
      tags:
      - login
  /nftProjects:
    get:
      consumes:
      - '*/*'
      description: fetch limited nft projects
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: nftProjects
      tags:
      - nftProjects
  /renewAccess:
    post:
      consumes:
      - application/json
      description: renewAccess
      parameters:
      - description: refreshToken
        in: body
        name: refreshToken
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.renewAccessTokenResponse'
        "201":
          description: Created
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: renewAccess
      tags:
      - renewAccess
schemes:
- http
swagger: "2.0"
