basePath: /
definitions:
  api.userResponse:
    type: object
host: localhost:1323
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Ifandonlyif API
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - '*/*'
      description: get the status of server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show the status of server.
      tags:
      - root
  /createUser:
    post:
      consumes:
      - application/json
      description: create user by params
      parameters:
      - description: fullName
        in: formData
        name: fullName
        required: true
        type: string
      - description: walletAddress
        in: formData
        name: walletAddress
        required: true
        type: string
      - description: countryCode
        in: formData
        name: countryCode
        required: true
        type: string
      - description: emailAddress
        in: formData
        name: emailAddress
        required: true
        type: string
      - description: twitterName
        in: formData
        name: twitterName
        required: true
        type: string
      - description: imageUri
        in: formData
        name: imageUri
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.userResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create An User
      tags:
      - createUser
schemes:
- http
swagger: "2.0"
