basePath: /
definitions:
  api.userResponse:
    properties:
      country_code:
        type: string
      created_at:
        type: string
      email_address:
        type: string
      full_name:
        type: string
      image_uri:
        type: string
      twitter_name:
        type: string
      wallet_address:
        type: string
    type: object
host: localhost:1323
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Ifandonlyif API
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - '*/*'
      description: get the status of server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show the status of server.
      tags:
      - root
  /createUser:
    post:
      consumes:
      - application/json
      description: create user by params
      parameters:
      - description: FullName
        in: formData
        name: FullName
        required: true
        type: string
      - description: WalletAddress
        in: formData
        name: WalletAddress
        required: true
        type: string
      - description: CountryCode
        in: formData
        name: CountryCode
        required: true
        type: string
      - description: EmailAddress
        in: formData
        name: EmailAddress
        required: true
        type: string
      - description: TwitterName
        in: formData
        name: TwitterName
        required: true
        type: string
      - description: ImageUri
        in: formData
        name: ImageUri
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.userResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create An User
      tags:
      - createUser
schemes:
- http
swagger: "2.0"
